# Generated by Django 4.0.1 on 2022-03-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pets',
            options={'ordering': ('-created_date',)},
        ),
    ]
